#!/bin/bash -xe
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
yum -y update
yum -y install java-1.8.0-openjdk-devel git docker
systemctl daemon-reload
systemctl start docker
echo "Done! user-data!"